### ISSUE TITLE
API endpoints for Power BI

### ISSUE THREAD

**Issue by askbulle** [equinor/flyt#160]
**User story**
As an end-user or leader I want to bring statistical VSM data to other tools, e.g. Power BI dashboards so that I can visualise current process health, improvement pace and use the data to ensure progress

**Requirements**
- [ ] Data setup to contextualise the data (MVP according to existing Power BI needs)
- [ ] GDPR is not violated (e.g. user data in the changelog)

**Comment by SjoenH** [comment]
# Virtual sql-table-views vs API-access.
We talked about if a proper api would be better. I'm leaning towards it since that would be a more proper way to do it for everyone...

Also, some GDPR things to consider. What is considered sensitive data? Names, and timestamps in the change-log could be used to check when people are working etc...

# The importance of free data
Might lead to higher adoption and usage.
Supporting the power-users. 💪 -> Value

**Comment by knudsvik** [comment]
@Magos @SjoenH : I have discussed use of API's in Power Bi with a colleague who tells me some API's are very straightforward to connect to from Power BI, such as the Centuries API (api.centuries.equinor.com). So I agree with @SjoenH here that we should just go for that from the start. I guess we can start with a simple endpoint with some basic data to verify and then gradually improve it based on need?

**Comment by Magos** [comment]
Desired statistics:

- A process listing with additional statistics : 
 - Subactivity count
 - Task counts by category & Solved/unsolved
 - Update times
- A label listing with the connected projects 
 - Label text, project ID numbers

**Comment by knudsvik** [comment]
@Magos For the changelog I am currently using the following SQL query: 

`SELECT [fkVsm], [ChangeDate] As Updated, [UserIdentity] As UpdatedBy
  FROM [dbo].[ChangeLog]
  WHERE fkVsm is not null
UNION ALL

SELECT [PkVsm] As fkVsm,[Updated],[UpdatedBy]
FROM [dbo].[VSM]
  FOR SYSTEM_TIME ALL
where updated > '2022-03-16 10:47'

order by ChangeDate desc`

It is however returning short names. To be safer wrt GDPR I would rather have a UUID or similar representing the user instead of the shortname.

**Comment by knudsvik** [comment]
I have troubles testing these, seems like an access issue, let's have a chat @Magos

**Comment by SjoenH** [comment]
@anheri @pagodo :wave: We might need some input here...

How would you open the API for everyone in the Equinor tenant? Specifically for use in PowerBi.

**Comment by Magos** [comment]
Thorjan has mentioned being able to use the Organizational Account method offered by PowerBI in the [Centuries API](https://api.centuries.equinor.com/index.html). 
Looking at their code, all [their controllers have a [Connect2DbAsUser] attribute](https://github.com/equinor/centuries/blob/3afac38fa70815c591ee803cc89efebe0ce47744/web/CenturiesWebApi/Controllers/Internal/Exploration/ScenarioSegmentController.cs)  which I'm not entirely sure where is defined yet. For the statistics controller this method might actually work, as I've defined these statistics views with a GRANT READ TO PUBLIC permission.

**Comment by knudsvik** [comment]
@Magos Any updates here?

**Comment by HavardNot** [comment]
Created new endpoints listed here:
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/767a92ae-8de7-486f-b5a2-07486fb00639">

The endpoints provide the data listed in this comment, except for "to be" as it is deprecated: https://github.com/equinor/flyt/issues/160#issuecomment-1054054044

See illustration of data flow here for guidelines for other data that is wanted. Not all data is available to the flyt-api so it may need to be sourced elsewhere.
![image (1)](https://github.com/user-attachments/assets/de2d5334-347a-4a86-888e-8529fac9f3fe)
