### ISSUE TITLE
Choice diamond pre-fillled with arrows 

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#416]
**User input 1 (by FL- sharepoint ID144):**
As a user of Flyt I would benefit of having arrows (◀▶) pre-inserted in the "selector"/Choice element when doing an VSM so save time when pointing towards sub-processes.

**Comment by SjoenH** [comment]
If I understand this correctly, we could pre-fill the choices with the arrow icons. That itself is a quick fix.

Though this would also be covered by #185

**Comment by askbulle** [comment]
@dansvend @SjoenH Kor Quick Fix er dette? Realistisk å release saman med linker for å feire 500 users?

**Comment by SjoenH** [comment]
Depends on how we want to solve it. 

Adding some default text to the choice when adding it is a quick fix. < 1 day (Still need to decide on some details here)

I'm adding support for lines between cards with support for labels (in #296 ), then we could mark the choice lines with yes and no, which seems to cover what the user wants.

So we might want to put this on hold until we support drawing lines, just so that we don't do the same work multiple times. 🤔

**Comment by KaterynaBasik** [comment]
I guess this might be closed as completed in #185 
Do you agree @askbulle ?
