### ISSUE TITLE
Upgrade Next.js, EDS, React and TypeScript packages

### ISSUE THREAD

**Issue by dansvend** [equinor/flyt#567]
We're currently running Next.js version 12, which should be upgraded to version 13.

Here is a guide: [Upgrading from 12 to 13](https://nextjs.org/docs/pages/building-your-application/upgrading/version-13)

**Comment by nesadrian** [comment]
Next version 14 has released since this issue was created so we will be upgrading to 14, as discussed. 
- Upgrading to React 18.2.0 is recommended as part of this process.
- Upgrading TypeScript to 5.3.3 is recommended as a part of the React upgrade.
- The TypeScript upgrade causes errors in our current EDS packages so I will also upgrade this to 0.35.1, which is long overdue anyways.

**Comment by nesadrian** [comment]
@SayyareHamit This is ready for test in [https://test.flyt.equinor.com/](https://test.flyt.equinor.com/) 

This upgrade affects a lot of parts of the web app. The whole app should be tested, but pay close attention to buttons that redirects the user and input fields.

We have migrated to a newer version of EDS so some things will have different styling, like the line under the search bar on the front page. Feel free to ask if you don't know if it's a bug or new EDS styling 👍

**Comment by SayyareHamit** [comment]
Works good in Test. @nesadrian 🐱‍💻
