### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by dansvend** [equinor/flyt#575]
To make sure all issues have the correct labels in GitHub , we need to make sure we only keep the labels we need and that we update the labels on an issue when the state changes. For example that issues which no longer needs a design has the `needs design` label removed by the designer to visualise in the board that the need for design on that issue is no longer present.

- [x] Remove unnecessary labels
- [x] Add needed labels
- [x] Document label strategy
- [x] Go through all issue and make sure they have the right labels

**Comment by nesadrian** [comment]
I have:
- Removed "CRITICAL" since we use priority
- Removed "hot-fix" since we have "quick-fix"
- Updated all label descriptions

I also want to change "enhancement" to "feature". I think enhancement is too broad of a term and this leads to this label being used on issues where there are other labels that would be a better fit. What do you think about this @KaterynaBasik ?

**Comment by KaterynaBasik** [comment]
It seems to me that change "enhancement" to "feature" is a good idea. However, we aim to have the same set of labels for all our  team's repositories for convinience. If you want to change, you'll need to change it eberywhere :)

**Comment by nesadrian** [comment]
I just checked their board and their tag is called "feat". I'm changing ours to the same.
