### ISSUE TITLE
Migration script: Choice children order

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#681]
**Describe the bug**
The order of choices children are different in prod and poc-qa. This is an issue because some users have written text such as "◀ Yes ▶ No" on the choice card itself and is reliant on the childrens order.

**To Reproduce**
Go to process 1919 and look at the "Application on life cycle" choice. Compare it in the two environments.

**Comment by nesadrian** [comment]
This should be the backend priority for Flyt right now. Great if one of you can take a look at it when you have time.

**Comment by HaakonSvane** [comment]
@anheri I see two possible ways to solve this in the migration script:
1. we insert a "do nothing" card for each existing choice node with only one option. Not very nice from both a user and a perfectionist perspective.
2. We migrate all choice verticies to have a "option" property so that the condition is stored on the vertex and not on the textfield on the choice node. This will require manual intervention.
 

Regarding the second alternative, do we know how many choice nodes are affected by this issue?

One option, in case there are many, is that we tag the problematic choice nodes and require the users to fix the issue themselves. Will require some frontend work as well.

**Comment by anheri** [comment]
@HaakonSvane I think you're refering to a different problem... the one with 1 choice alternative...
This problem refer to any choice... And I dont think its related to your migrate script... I think (hope) it's because of a bad migration... I'll try to re-import the 1919 process, to see if it is resolved...

**Comment by HaakonSvane** [comment]
My bad. Been on my mind a lot lately 👹

**Comment by anheri** [comment]
have re-imported process 1919, and it looks good... As I suspected the import of 1919 must at have been faulty.

**Comment by QiJin-Bouvet** [comment]
Tested in qa-graph-poc.
Process 1919 has the same Yes and No branches for choice card 'Application on Life cycle list?' as in Production now.
